### ISSUE TITLE
Code help

### ISSUE THREAD

**Issue by lmd123123** [wadx2019/rpo#1]
Hi Dr. Ding, can you provide the code for the safe reinforcement learning method in the comparative experiment? (CPO, CUP, safety laye any of them is OK, about OPF with Battery Energy Storage environment), if you are willing to provide it. Thank you very much!

**Comment by wadx2019** [comment]
Of course, OK! However, I didn't clean up that part of the code and it could be a little confusing for you. So I am not going to present them in github. But if you insist, please send me your email address and I will email it to you.

**Comment by lmd123123** [comment]
E-mail: 625087842@qq.com
It would be better to provide a simple readme for the code.
Thank you very much for your help. Best wishes!

**Comment by wadx2019** [comment]
sent
